# See https://finnian.io/blog/ssl-with-docker-swarm-lets-encrypt-and-nginx/
# and http://docs.gunicorn.org/en/stable/deploy.html
version: '3.2'
services:
    nginx:
        image: nginx:stable-alpine
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
            - /usr/share/nginx/html:/usr/share/nginx/html
            - /etc/nginx:/etc/nginx:ro
        ports:
            - 80:80
            - 443:443
        restart: on-failure

    rocket2:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 5000:5000
        environment:
            - SLACK_NOTIFICATION_CHANNEL=${SLACK_NOTIFICATION_CHANNEL}
            - SLACK_ANNOUNCEMENT_CHANNEL=${SLACK_ANNOUNCEMENT_CHANNEL}
            - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
            - SLACK_API_TOKEN=${SLACK_API_TOKEN}
            - GITHUB_APP_ID=${GITHUB_APP_ID}
            - GITHUB_ORG_NAME=${GITHUB_ORG_NAME}
            - GITHUB_WEBHOOK_ENDPT=${GITHUB_WEBHOOK_ENDPT}
            - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
            - GITHUB_KEY=${GITHUB_KEY}
            - AWS_ACCESS_KEYID=${AWS_ACCESS_KEYID}
            - AWS_SECRET_KEY=${AWS_SECRET_KEY}
            - AWS_USERS_TABLE=${AWS_USERS_TABLE}
            - AWS_TEAMS_TABLE=${AWS_TEAMS_TABLE}
            - AWS_PROJECTS_TABLE=${AWS_PROJECTS_TABLE}
            - AWS_REGION=${AWS_REGION}
            - AWS_LOCAL=${AWS_LOCAL}
        restart: on-failure
