# See https://finnian.io/blog/ssl-with-docker-swarm-lets-encrypt-and-nginx/
# and http://docs.gunicorn.org/en/stable/deploy.html
version: '3.2'
services:
    nginx:
        image: nginx:stable-alpine
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
            - /usr/share/nginx/html:/usr/share/nginx/html
            - /etc/nginx:/etc/nginx:ro
        ports:
            - 80:80
            - 443:443
        restart: on-failure

    rocket2:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 5000:5000
        environment:
            - SLACK_NOTIFICATION_CHANNEL=${SLACK_NOTIFICATION_CHANNEL}
            - SLACK_ANNOUNCEMENT_CHANNEL=${SLACK_ANNOUNCEMENT_CHANNEL}
            - SLACK_PAIRING_CHANNEL=${SLACK_PAIRING_CHANNEL}
            - SLACK_PAIRING_FREQUENCY=${SLACK_PAIRING_FREQUENCY}
            - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
            - SLACK_API_TOKEN=${SLACK_API_TOKEN}
            - GITHUB_APP_ID=${GITHUB_APP_ID}
            - GITHUB_ORG_NAME=${GITHUB_ORG_NAME}
            - GITHUB_WEBHOOK_ENDPT=${GITHUB_WEBHOOK_ENDPT}
            - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
            - GITHUB_DEFAULT_TEAM_NAME=${GITHUB_DEFAULT_TEAM_NAME}
            - GITHUB_ADMIN_TEAM_NAME=${GITHUB_ADMIN_TEAM_NAME}
            - GITHUB_LEADS_TEAM_NAME=${GITHUB_LEADS_TEAM_NAME}
            - GITHUB_KEY=${GITHUB_KEY}
            - AWS_ACCESS_KEYID=${AWS_ACCESS_KEYID}
            - AWS_SECRET_KEY=${AWS_SECRET_KEY}
            - AWS_USERS_TABLE=${AWS_USERS_TABLE}
            - AWS_TEAMS_TABLE=${AWS_TEAMS_TABLE}
            - AWS_PAIRINGS_TABLE=${AWS_PAIRINGS_TABLE}
            - AWS_PROJECTS_TABLE=${AWS_PROJECTS_TABLE}
            - AWS_REGION=${AWS_REGION}
            - AWS_LOCAL=${AWS_LOCAL}
            - GCP_SERVICE_ACCOUNT_CREDENTIALS=${GCP_SERVICE_ACCOUNT_CREDENTIALS}
            - GCP_SERVICE_ACCOUNT_SUBJECT=${GCP_SERVICE_ACCOUNT_SUBJECT}
        restart: on-failure

    certbot:
        image: certbot/certbot
        restart: on-failure
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
            - /var/lib/letsencrypt:/var/lib/letsencrypt
            - /usr/share/nginx/html:/usr/share/nginx/html
        entrypoint: "/bin/sh -c 'trap exit TERM; sleep 12h; while :; do certbot renew --webroot -w /usr/share/nginx/html; sleep 12h & wait $${!}; done;'"
