name: Issue opened

on:
  issues:
    types: [opened]

jobs:
  move-issue-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: Rocket 2 Planning
          column: Needs triage
          repo-token: ${{ secrets.GITHUB_TOKEN }}
