name: Publish Docker image
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to gcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ubclaunchpad
          password: ${{ secrets.GH_PACKAGES_TOKEN }}
      - name: Build and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          registry: ghcr.io
          push: true
          tags: |
            ghcr.io/ubclaunchpad/rocket2:latest
