name: Pull request

on: pull_request

env:
  PIPENV_CACHE_DIR: ${{ secrets.PIPENV_CACHE_DIR }}

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Cache Dependencies
      uses: actions/cache@v2
      with:
        path: ${{ secrets.PIPENV_CACHE_DIR }}
        key: ${{ runner.os }}-build-${{ hashFiles('Pipfile*') }}
        restore-keys: |
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install Dependencies
      env:
        PIPENV_CACHE_DIR: ${{ secrets.PIPENV_CACHE_DIR }}
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jre
        python -m pip install --upgrade pipenv
        pip install pipenv
        pipenv install --dev
    - name: Start local DynamoDB
      run: scripts/download_dynamodb_and_run.sh
    - name: Test everything
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        scripts/build_check.sh
        pipenv run codecov --required
