name: Pull request

on: pull_request

env:
  PIPENV_CACHE_DIR: ${{ secrets.PIPENV_CACHE_DIR }}
  PIPENV_IGNORE_PIPFILE: true

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Cache Pipfile Dependencies
      uses: actions/cache@v2
      with:
        path: ${{ secrets.PIPENV_CACHE_DIR }}
        key: ${{ runner.os }}-build-pipfile-${{ hashFiles('Pipfile*') }}
        restore-keys: |
          ${{ runner.os }}-build-pipfile-
    - name: Cache pip Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-build-pip-${{ hashFiles('Pipfile*') }}
        restore-keys: |
          ${{ runner.os }}-build-pip-
    - name: Cache local DDB
      uses: actions/cache@v2
      with:
        path: DynamoDB
        key: ddb
    - name: Install Dependencies
      run: |
        pip install pipenv
        pipenv install --dev
    - name: Start local DynamoDB
      run: scripts/download_dynamodb_and_run.sh
    - name: Test everything
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        scripts/build_check.sh
        pipenv run codecov --required
