name: Pull request lint/test

on: pull_request

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Set up Python 3.8
              uses: actions/setup-python@v1
              with:
                  python-version: 3.8
            - name: Install Dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y default-jre rubygems
                  python -m pip install --upgrade pipenv
                  pip install pipenv
                  pipenv install --dev
            - name: Start local DynamoDB
              run: scripts/download_dynamodb_and_run.sh
            - name: Test everything
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
              run: |
                  scripts/build_check.sh
                  pipenv run codecov --required
